name: Webhook Action

on:
  push:
    branches:
      - '*'

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Webhook Action
        uses: joelwmale/webhook-action@2.3.2
        with:
          url: 'https://afc8-2001-b07-5d29-eaa8-39ad-3b3b-ff4c-d6bb.ngrok-free.app/api/webhooks/knowhow/channels/5886072B-AE11-4BF0-5FB6-08DBA2977582/feedback'
          headers: '{"Pat": "12f37b77d2a344f48fde7ca0d5531be3"}'
          body: '${{ github.event }}'   
